### ISSUE TITLE
Fix the website 

### ISSUE THREAD

**Issue by priyankarpal** [Sheepeer/Sheepeer-site#12]
I noticed that this website left portion UI is not good. I think you have to change it to look better.

![image](https://user-images.githubusercontent.com/88102392/220311061-f3d5915a-dc92-4bfa-bda2-09ba56445ea3.png)

**Comment by MattinaYang** [comment]
> I noticed that this website left portion UI is not good. I think you have to change it to look better.
> 
> ![image](https://user-images.githubusercontent.com/88102392/220311061-f3d5915a-dc92-4bfa-bda2-09ba56445ea3.png)

Thanks!  I will fix this soon!  I haven't finish this website yet, so maybe this repo should be public after completed 😃
